/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingArAlbumsRouteImport } from './routes/wedding-ar-albums'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AugmentedRealityPhotoAlbumRouteImport } from './routes/augmented-reality-photo-album'
import { Route as ArWeddingInvitationsRouteImport } from './routes/ar-wedding-invitations'
import { Route as ArGreetingCardsRouteImport } from './routes/ar-greeting-cards'
import { Route as ArBusinessCardsRouteImport } from './routes/ar-business-cards'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArSlugRouteImport } from './routes/ar.$slug'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedMfaRouteImport } from './routes/_authenticated/mfa'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ArAlbumSlugRouteImport } from './routes/ar.album.$slug'
import { Route as AuthenticatedDashboardMarkerTestsRouteImport } from './routes/_authenticated/dashboard.marker-tests'
import { Route as AuthenticatedDashboardLicensesRouteImport } from './routes/_authenticated/dashboard.licenses'
import { Route as AuthenticatedDashboardExperiencesRouteImport } from './routes/_authenticated/dashboard.experiences'
import { Route as AuthenticatedDashboardAuditRouteImport } from './routes/_authenticated/dashboard.audit'
import { Route as AuthenticatedDashboardApprovalsRouteImport } from './routes/_authenticated/dashboard.approvals'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardActivationsRouteImport } from './routes/_authenticated/dashboard.activations'
import { Route as AuthenticatedDashboardAlbumsIndexRouteImport } from './routes/_authenticated/dashboard.albums.index'
import { Route as ApiPublicLicenseActivateRouteImport } from './routes/api/public/license/activate'
import { Route as AuthenticatedDashboardAlbumsNewRouteImport } from './routes/_authenticated/dashboard.albums.new'

const WeddingArAlbumsRoute = WeddingArAlbumsRouteImport.update({
  id: '/wedding-ar-albums',
  path: '/wedding-ar-albums',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AugmentedRealityPhotoAlbumRoute =
  AugmentedRealityPhotoAlbumRouteImport.update({
    id: '/augmented-reality-photo-album',
    path: '/augmented-reality-photo-album',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArWeddingInvitationsRoute = ArWeddingInvitationsRouteImport.update({
  id: '/ar-wedding-invitations',
  path: '/ar-wedding-invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ArGreetingCardsRoute = ArGreetingCardsRouteImport.update({
  id: '/ar-greeting-cards',
  path: '/ar-greeting-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ArBusinessCardsRoute = ArBusinessCardsRouteImport.update({
  id: '/ar-business-cards',
  path: '/ar-business-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArSlugRoute = ArSlugRouteImport.update({
  id: '/ar/$slug',
  path: '/ar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMfaRoute = AuthenticatedMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ArAlbumSlugRoute = ArAlbumSlugRouteImport.update({
  id: '/ar/album/$slug',
  path: '/ar/album/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardMarkerTestsRoute =
  AuthenticatedDashboardMarkerTestsRouteImport.update({
    id: '/marker-tests',
    path: '/marker-tests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLicensesRoute =
  AuthenticatedDashboardLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardExperiencesRoute =
  AuthenticatedDashboardExperiencesRouteImport.update({
    id: '/experiences',
    path: '/experiences',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAuditRoute =
  AuthenticatedDashboardAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApprovalsRoute =
  AuthenticatedDashboardApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardActivationsRoute =
  AuthenticatedDashboardActivationsRouteImport.update({
    id: '/activations',
    path: '/activations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAlbumsIndexRoute =
  AuthenticatedDashboardAlbumsIndexRouteImport.update({
    id: '/albums/',
    path: '/albums/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicLicenseActivateRoute =
  ApiPublicLicenseActivateRouteImport.update({
    id: '/api/public/license/activate',
    path: '/api/public/license/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardAlbumsNewRoute =
  AuthenticatedDashboardAlbumsNewRouteImport.update({
    id: '/albums/new',
    path: '/albums/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar-business-cards': typeof ArBusinessCardsRoute
  '/ar-greeting-cards': typeof ArGreetingCardsRoute
  '/ar-wedding-invitations': typeof ArWeddingInvitationsRoute
  '/augmented-reality-photo-album': typeof AugmentedRealityPhotoAlbumRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-ar-albums': typeof WeddingArAlbumsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/mfa': typeof AuthenticatedMfaRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/ar/$slug': typeof ArSlugRoute
  '/dashboard/activations': typeof AuthenticatedDashboardActivationsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/approvals': typeof AuthenticatedDashboardApprovalsRoute
  '/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/dashboard/experiences': typeof AuthenticatedDashboardExperiencesRoute
  '/dashboard/licenses': typeof AuthenticatedDashboardLicensesRoute
  '/dashboard/marker-tests': typeof AuthenticatedDashboardMarkerTestsRoute
  '/ar/album/$slug': typeof ArAlbumSlugRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/albums/new': typeof AuthenticatedDashboardAlbumsNewRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/dashboard/albums/': typeof AuthenticatedDashboardAlbumsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ar-business-cards': typeof ArBusinessCardsRoute
  '/ar-greeting-cards': typeof ArGreetingCardsRoute
  '/ar-wedding-invitations': typeof ArWeddingInvitationsRoute
  '/augmented-reality-photo-album': typeof AugmentedRealityPhotoAlbumRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-ar-albums': typeof WeddingArAlbumsRoute
  '/mfa': typeof AuthenticatedMfaRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/ar/$slug': typeof ArSlugRoute
  '/dashboard/activations': typeof AuthenticatedDashboardActivationsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/approvals': typeof AuthenticatedDashboardApprovalsRoute
  '/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/dashboard/experiences': typeof AuthenticatedDashboardExperiencesRoute
  '/dashboard/licenses': typeof AuthenticatedDashboardLicensesRoute
  '/dashboard/marker-tests': typeof AuthenticatedDashboardMarkerTestsRoute
  '/ar/album/$slug': typeof ArAlbumSlugRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/albums/new': typeof AuthenticatedDashboardAlbumsNewRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/dashboard/albums': typeof AuthenticatedDashboardAlbumsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ar-business-cards': typeof ArBusinessCardsRoute
  '/ar-greeting-cards': typeof ArGreetingCardsRoute
  '/ar-wedding-invitations': typeof ArWeddingInvitationsRoute
  '/augmented-reality-photo-album': typeof AugmentedRealityPhotoAlbumRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-ar-albums': typeof WeddingArAlbumsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/mfa': typeof AuthenticatedMfaRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/ar/$slug': typeof ArSlugRoute
  '/_authenticated/dashboard/activations': typeof AuthenticatedDashboardActivationsRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/approvals': typeof AuthenticatedDashboardApprovalsRoute
  '/_authenticated/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/_authenticated/dashboard/experiences': typeof AuthenticatedDashboardExperiencesRoute
  '/_authenticated/dashboard/licenses': typeof AuthenticatedDashboardLicensesRoute
  '/_authenticated/dashboard/marker-tests': typeof AuthenticatedDashboardMarkerTestsRoute
  '/ar/album/$slug': typeof ArAlbumSlugRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/albums/new': typeof AuthenticatedDashboardAlbumsNewRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/_authenticated/dashboard/albums/': typeof AuthenticatedDashboardAlbumsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ar-business-cards'
    | '/ar-greeting-cards'
    | '/ar-wedding-invitations'
    | '/augmented-reality-photo-album'
    | '/auth'
    | '/gallery'
    | '/scan'
    | '/sitemap.xml'
    | '/wedding-ar-albums'
    | '/dashboard'
    | '/mfa'
    | '/pending'
    | '/ar/$slug'
    | '/dashboard/activations'
    | '/dashboard/analytics'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/experiences'
    | '/dashboard/licenses'
    | '/dashboard/marker-tests'
    | '/ar/album/$slug'
    | '/dashboard/'
    | '/dashboard/albums/new'
    | '/api/public/license/activate'
    | '/dashboard/albums/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ar-business-cards'
    | '/ar-greeting-cards'
    | '/ar-wedding-invitations'
    | '/augmented-reality-photo-album'
    | '/auth'
    | '/gallery'
    | '/scan'
    | '/sitemap.xml'
    | '/wedding-ar-albums'
    | '/mfa'
    | '/pending'
    | '/ar/$slug'
    | '/dashboard/activations'
    | '/dashboard/analytics'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/experiences'
    | '/dashboard/licenses'
    | '/dashboard/marker-tests'
    | '/ar/album/$slug'
    | '/dashboard'
    | '/dashboard/albums/new'
    | '/api/public/license/activate'
    | '/dashboard/albums'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ar-business-cards'
    | '/ar-greeting-cards'
    | '/ar-wedding-invitations'
    | '/augmented-reality-photo-album'
    | '/auth'
    | '/gallery'
    | '/scan'
    | '/sitemap.xml'
    | '/wedding-ar-albums'
    | '/_authenticated/dashboard'
    | '/_authenticated/mfa'
    | '/_authenticated/pending'
    | '/ar/$slug'
    | '/_authenticated/dashboard/activations'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/approvals'
    | '/_authenticated/dashboard/audit'
    | '/_authenticated/dashboard/experiences'
    | '/_authenticated/dashboard/licenses'
    | '/_authenticated/dashboard/marker-tests'
    | '/ar/album/$slug'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/albums/new'
    | '/api/public/license/activate'
    | '/_authenticated/dashboard/albums/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArBusinessCardsRoute: typeof ArBusinessCardsRoute
  ArGreetingCardsRoute: typeof ArGreetingCardsRoute
  ArWeddingInvitationsRoute: typeof ArWeddingInvitationsRoute
  AugmentedRealityPhotoAlbumRoute: typeof AugmentedRealityPhotoAlbumRoute
  AuthRoute: typeof AuthRoute
  GalleryRoute: typeof GalleryRoute
  ScanRoute: typeof ScanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingArAlbumsRoute: typeof WeddingArAlbumsRoute
  ArSlugRoute: typeof ArSlugRoute
  ArAlbumSlugRoute: typeof ArAlbumSlugRoute
  ApiPublicLicenseActivateRoute: typeof ApiPublicLicenseActivateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-ar-albums': {
      id: '/wedding-ar-albums'
      path: '/wedding-ar-albums'
      fullPath: '/wedding-ar-albums'
      preLoaderRoute: typeof WeddingArAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/augmented-reality-photo-album': {
      id: '/augmented-reality-photo-album'
      path: '/augmented-reality-photo-album'
      fullPath: '/augmented-reality-photo-album'
      preLoaderRoute: typeof AugmentedRealityPhotoAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar-wedding-invitations': {
      id: '/ar-wedding-invitations'
      path: '/ar-wedding-invitations'
      fullPath: '/ar-wedding-invitations'
      preLoaderRoute: typeof ArWeddingInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar-greeting-cards': {
      id: '/ar-greeting-cards'
      path: '/ar-greeting-cards'
      fullPath: '/ar-greeting-cards'
      preLoaderRoute: typeof ArGreetingCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar-business-cards': {
      id: '/ar-business-cards'
      path: '/ar-business-cards'
      fullPath: '/ar-business-cards'
      preLoaderRoute: typeof ArBusinessCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/$slug': {
      id: '/ar/$slug'
      path: '/ar/$slug'
      fullPath: '/ar/$slug'
      preLoaderRoute: typeof ArSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mfa': {
      id: '/_authenticated/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof AuthenticatedMfaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/ar/album/$slug': {
      id: '/ar/album/$slug'
      path: '/ar/album/$slug'
      fullPath: '/ar/album/$slug'
      preLoaderRoute: typeof ArAlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/marker-tests': {
      id: '/_authenticated/dashboard/marker-tests'
      path: '/marker-tests'
      fullPath: '/dashboard/marker-tests'
      preLoaderRoute: typeof AuthenticatedDashboardMarkerTestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/licenses': {
      id: '/_authenticated/dashboard/licenses'
      path: '/licenses'
      fullPath: '/dashboard/licenses'
      preLoaderRoute: typeof AuthenticatedDashboardLicensesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/experiences': {
      id: '/_authenticated/dashboard/experiences'
      path: '/experiences'
      fullPath: '/dashboard/experiences'
      preLoaderRoute: typeof AuthenticatedDashboardExperiencesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/audit': {
      id: '/_authenticated/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof AuthenticatedDashboardAuditRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/approvals': {
      id: '/_authenticated/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof AuthenticatedDashboardApprovalsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/activations': {
      id: '/_authenticated/dashboard/activations'
      path: '/activations'
      fullPath: '/dashboard/activations'
      preLoaderRoute: typeof AuthenticatedDashboardActivationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/albums/': {
      id: '/_authenticated/dashboard/albums/'
      path: '/albums'
      fullPath: '/dashboard/albums/'
      preLoaderRoute: typeof AuthenticatedDashboardAlbumsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/license/activate': {
      id: '/api/public/license/activate'
      path: '/api/public/license/activate'
      fullPath: '/api/public/license/activate'
      preLoaderRoute: typeof ApiPublicLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/albums/new': {
      id: '/_authenticated/dashboard/albums/new'
      path: '/albums/new'
      fullPath: '/dashboard/albums/new'
      preLoaderRoute: typeof AuthenticatedDashboardAlbumsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardActivationsRoute: typeof AuthenticatedDashboardActivationsRoute
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardApprovalsRoute: typeof AuthenticatedDashboardApprovalsRoute
  AuthenticatedDashboardAuditRoute: typeof AuthenticatedDashboardAuditRoute
  AuthenticatedDashboardExperiencesRoute: typeof AuthenticatedDashboardExperiencesRoute
  AuthenticatedDashboardLicensesRoute: typeof AuthenticatedDashboardLicensesRoute
  AuthenticatedDashboardMarkerTestsRoute: typeof AuthenticatedDashboardMarkerTestsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAlbumsNewRoute: typeof AuthenticatedDashboardAlbumsNewRoute
  AuthenticatedDashboardAlbumsIndexRoute: typeof AuthenticatedDashboardAlbumsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardActivationsRoute:
      AuthenticatedDashboardActivationsRoute,
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardApprovalsRoute: AuthenticatedDashboardApprovalsRoute,
    AuthenticatedDashboardAuditRoute: AuthenticatedDashboardAuditRoute,
    AuthenticatedDashboardExperiencesRoute:
      AuthenticatedDashboardExperiencesRoute,
    AuthenticatedDashboardLicensesRoute: AuthenticatedDashboardLicensesRoute,
    AuthenticatedDashboardMarkerTestsRoute:
      AuthenticatedDashboardMarkerTestsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAlbumsNewRoute: AuthenticatedDashboardAlbumsNewRoute,
    AuthenticatedDashboardAlbumsIndexRoute:
      AuthenticatedDashboardAlbumsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedMfaRoute: typeof AuthenticatedMfaRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedMfaRoute: AuthenticatedMfaRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArBusinessCardsRoute: ArBusinessCardsRoute,
  ArGreetingCardsRoute: ArGreetingCardsRoute,
  ArWeddingInvitationsRoute: ArWeddingInvitationsRoute,
  AugmentedRealityPhotoAlbumRoute: AugmentedRealityPhotoAlbumRoute,
  AuthRoute: AuthRoute,
  GalleryRoute: GalleryRoute,
  ScanRoute: ScanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingArAlbumsRoute: WeddingArAlbumsRoute,
  ArSlugRoute: ArSlugRoute,
  ArAlbumSlugRoute: ArAlbumSlugRoute,
  ApiPublicLicenseActivateRoute: ApiPublicLicenseActivateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
